import Foundation

// Official HAA 21st Biennial Convention program — Jul 2–5, 2026
extension ConventionData {

    static let thursdayEvents: [ScheduleEvent] = [
        ScheduleEvent(time: "11:00 AM – 5:00 PM", title: "Youth Activity", kannada: "ಯುವ ಚಟುವಟಿಕೆ", tag: .youth,
                      details: "Pickleball, badminton, volleyball, and cricket nets at Play N Thrive. Food and drinks provided for all youth participants.",
                      icon: "sportscourt.fill", venue: "Play N Thrive Club, Naperville", isHighlight: true),
        ScheduleEvent(time: "4:00 – 10:00 PM", title: "Registration & Check-In", kannada: "ನೋಂದಣಿ ಮತ್ತು ಚೆಕ್-ಇನ್", tag: .social,
                      details: "Convention registration and check-in at the Check-in Desk.",
                      icon: "person.crop.circle.badge.checkmark", venue: "Check-in Desk", isHighlight: true),
        ScheduleEvent(time: "6:00 – 8:00 PM", title: "Welcome Reception & Meet-and-Greet", kannada: "ಸ್ವಾಗತ ಸಂಭ್ರಮ ಮತ್ತು ಪರಿಚಯ", tag: .social,
                      details: "Welcome reception and meet-and-greet with fellow attendees.",
                      icon: "hand.wave.fill", venue: "Ahichhatra Auditorium"),
    ]

    static let fridayEvents: [ScheduleEvent] = [
        ScheduleEvent(time: "8:00 – 9:30 AM", title: "Breakfast", kannada: "ಉಪಾಹಾರ", tag: .meal,
                      details: "Vegetarian breakfast.",
                      icon: "sunrise.fill", venue: "Annapoorna Bhojana Shale (Gym)"),
        ScheduleEvent(time: "8:30 – 11:00 AM", title: "Gana Homa & Rudra Homa", kannada: "ಗಣ ಹೋಮ ಮತ್ತು ರುದ್ರ ಹೋಮ", tag: .vedic,
                      details: "Performed by learned priests.",
                      icon: "flame.fill", venue: "Havya Kavya Yaga Shale (Courtyard)", isHighlight: true),
        ScheduleEvent(time: "11:00 AM – 1:00 PM", title: "Havyaka Jaatre & Lunch", kannada: "ಹವ್ಯಕ ಜಾತ್ರೆ ಮತ್ತು ಭೋಜನ", tag: .social,
                      details: "Havyaka Jaatre community gathering in the corridor stalls, followed by lunch.",
                      icon: "person.3.fill", venue: "Jaatre Corridor & Annapoorna Bhojana Shale (Gym)"),
        ScheduleEvent(time: "11:00 – 11:45 AM", title: "Bhagavad Geetha / Vedantha Discussions", kannada: "ಭಗವದ್ಗೀತೆ / ವೇದಾಂತ ಚರ್ಚೆ", tag: .vedic,
                      details: "Moderator: Aparna Adkoli.",
                      icon: "text.book.closed.fill", venue: "Bharadvaja & Jamadagni Kutira"),
        ScheduleEvent(time: "12:00 – 12:45 PM", title: "Jyothishya Shastra", kannada: "ಜ್ಯೋತಿಷ್ಯ ಶಾಸ್ತ್ರ", tag: .vedic,
                      details: "By Smt. Suvarna Joshi. Moderator: Shivu Bhat.",
                      icon: "moon.stars.fill", venue: "Bharadvaja & Jamadagni Kutira"),
        ScheduleEvent(time: "1:00 – 3:30 PM", title: "Festive Procession", kannada: "ಉತ್ಸವ ಮೆರವಣಿಗೆ", tag: .ceremony,
                      details: "Opening procession in the Ahichhatra Auditorium.",
                      icon: "flag.fill", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "1:00 – 3:30 PM", title: "Invocation Dance", kannada: "ಆಹ್ವಾನ ನೃತ್ಯ", tag: .cultural,
                      details: "Invocation dance performance.",
                      icon: "figure.dance", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "1:00 – 3:30 PM", title: "National Anthem", kannada: "ರಾಷ್ಟ್ರಗೀತೆ", tag: .ceremony,
                      details: "National anthem presentation.",
                      icon: "music.note", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "1:00 – 3:30 PM", title: "Sabha Karyakrama — Program Agenda", kannada: "ಸಭಾ ಕಾರ್ಯಕ್ರಮ", tag: .ceremony,
                      details: "Official program agenda for the opening ceremony.",
                      icon: "list.bullet", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "1:00 – 3:30 PM", title: "Veda Ghosha by Learned Priests", kannada: "ವೇದ ಘೋಷ", tag: .vedic,
                      details: "Veda Ghosha by learned priests.",
                      icon: "flame.fill", venue: "Ahichhatra Auditorium", isHighlight: true),
        ScheduleEvent(time: "1:00 – 3:30 PM", title: "HAA President's Address", kannada: "ಅಧ್ಯಕ್ಷರ ಭಾಷಣ", tag: .ceremony,
                      details: "Welcome address opening the official convention program.",
                      icon: "person.wave.2.fill", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "1:00 – 3:30 PM", title: "Address by Chief Guest Vishweshwar Bhat", kannada: "ಮುಖ್ಯ ಅತಿಥಿ ಭಾಷಣ", tag: .ceremony,
                      details: "Editor in Chief, Vishwavani Kannada Daily News Paper, Bengaluru.",
                      icon: "mic.fill", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "1:00 – 3:30 PM", title: "HAA's 10-Year Vision", kannada: "ಹವ್ಯಕ ಅಸೋಸಿಯೇಷನ್ ೧೦ ವರ್ಷದ ದೃಷ್ಟಿ", tag: .meeting,
                      details: "Balakrishna Joshi, Chair, HAA Board of Trustees.",
                      icon: "chart.line.uptrend.xyaxis", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "1:00 – 3:30 PM", title: "Release of Havyasiri Smarana Sanchike", kannada: "ಹವ್ಯಸಿರಿ ಸ್ಮರಣ ಸಂಚಿಕೆ ಬಿಡುಗಡೆ", tag: .ceremony,
                      details: "Official release of the Havyasiri commemorative publication.",
                      icon: "book.fill", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "1:00 – 3:30 PM", title: "Sponsor Recognition Ceremony", kannada: "ಪ್ರಾಯೋಜಕರ ಗೌರವ", tag: .ceremony,
                      details: "Recognition of convention sponsors.",
                      icon: "heart.fill", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "1:00 – 3:30 PM", title: "Convention Theme Song Presentation", kannada: "ಸಮ್ಮೇಳನ ಥೀಮ್ ಸಾಂಗ್", tag: .cultural,
                      details: "Official unveiling of the Havyaka Samagama theme song.",
                      icon: "music.note", venue: "Ahichhatra Auditorium", isHighlight: true),
        ScheduleEvent(time: "1:00 – 3:30 PM", title: "Vote of Thanks", kannada: "ಧನ್ಯವಾದ", tag: .ceremony,
                      details: "HAA Secretary.",
                      icon: "hands.clap.fill", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "3:30 – 4:00 PM", title: "Tea Break", kannada: "ಚಹಾ ವಿರಾಮ", tag: .meal,
                      details: "Afternoon tea break.",
                      icon: "cup.and.saucer.fill", venue: "Havya Paakashale (Cafeteria)"),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Maya Leela — Dance Drama", kannada: "ಮಾಯಾ ಲೀಲಾ", tag: .cultural,
                      details: "Dance drama presentation by all chapter youth.",
                      icon: "theatermasks.fill", venue: "Ahichhatra Auditorium", isHighlight: true),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Havyakaru Naavu Havyakaru — Skit", kannada: "ಹವ್ಯಕರು ನಾವು ಹವ್ಯಕರು", tag: .cultural,
                      details: "Skit presentation.",
                      icon: "theatermasks.fill", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Folk Dance", kannada: "ಜಾನಪದ ನೃತ್ಯ", tag: .cultural,
                      details: "Folk dance by Northeast Chapter.",
                      icon: "figure.dance", chapter: "Northeast Chapter", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Bharatanatyam Dance", kannada: "ಭರತನಾಟ್ಯ", tag: .cultural,
                      details: "Bharatanatyam dance by Northern California Chapter.",
                      icon: "figure.dance", chapter: "Northern California Chapter", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Hange Heege... — Drama with Dance", kannada: "ಹಂಗೆ ಹೀಗೆ...", tag: .cultural,
                      details: "Drama with dance by MDC Cutters.",
                      icon: "theatermasks.fill", chapter: "MDC Cutters", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Awarding Competition Winners", kannada: "ಸ್ಪರ್ಧಾ ವಿಜೇತರಿಗೆ ಪ್ರಶಸ್ತಿ", tag: .ceremony,
                      details: "Recognition of competition winners.",
                      icon: "trophy.fill", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "7:00 PM – 12:30 AM", title: "Youth Outing — Chicago", kannada: "ಯುವ ಚಿಕಾಗೊ ಪ್ರವಾಸ", tag: .youth,
                      details: "Dinner at the beach, sightseeing tour with a stop at the Planetarium, then return to hotels and the venue.",
                      icon: "bus.fill", venue: "Chicago", isHighlight: true),
        ScheduleEvent(time: "7:30 – 9:00 PM", title: "Dinner", kannada: "ಭೋಜನ", tag: .meal,
                      details: "Traditional Havyaka feast.",
                      icon: "fork.knife", venue: "Annapoorna Bhojana Shale (Gym)"),
        ScheduleEvent(time: "9:00 – 10:30 PM", title: "Musical Night with Anuradha Bhat & Team", kannada: "ಅನುರಾಧಾ ಭಟ್ ಮತ್ತು ತಂಡದ ಸಂಗೀತ ರಾತ್ರಿ", tag: .concert,
                      details: "Special live concert by celebrated playback singer and accompanying artists from India.",
                      icon: "music.mic", venue: "Ahichhatra Auditorium", isHighlight: true),
    ]

    static let saturdayEvents: [ScheduleEvent] = [
        ScheduleEvent(time: "8:00 – 9:30 AM", title: "Breakfast", kannada: "ಉಪಾಹಾರ", tag: .meal,
                      details: "Vegetarian breakfast.",
                      icon: "sunrise.fill", venue: "Annapoorna Bhojana Shale (Gym)"),
        ScheduleEvent(time: "8:15 – 9:00 AM", title: "Havyaka Community Living After Retirement 55+", kannada: "ನಿವೃತ್ತಿ ನಂತರ ಹವ್ಯಕ ಸಮುದಾಯ ಜೀವನ", tag: .meeting,
                      details: "Moderator/Presenter: Shivu Bhat, Sadananda Bhat.",
                      icon: "person.2.fill", venue: "Bharadvaja & Jamadagni Kutira"),
        ScheduleEvent(time: "8:15 – 9:00 AM", title: "Havyaka Parent Network", kannada: "ಹವ್ಯಕ ಪೋಷಕರ ಜಾಲ", tag: .meeting,
                      details: "Moderator/Presenter: Sujnani Adkoli.",
                      icon: "person.3.fill", venue: "Bharadvaja & Jamadagni Kutira"),
        ScheduleEvent(time: "9:00 AM – 12:00 PM", title: "Veda Mantra by Students of HAA Veda Paathashaala", kannada: "ವೇದ ಮಂತ್ರ — ವೇದ ಪಾಠಶಾಲಾ ವಿದ್ಯಾರ್ಥಿಗಳು", tag: .vedic,
                      details: "Veda mantra recitation by students of HAA Veda Paathashaala.",
                      icon: "text.book.closed.fill", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "9:00 AM – 12:00 PM", title: "Video Divya Sandesha by Swamijis of Havyaka Mutts", kannada: "ಹವ್ಯಕ ಮಠಗಳ ಸ್ವಾಮೀಜಿಗಳ ದಿವ್ಯ ಸಂದೇಶ", tag: .vedic,
                      details: "Divine message video presentation by Swamijis of Havyaka Mutts.",
                      icon: "play.rectangle.fill", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "9:00 AM – 12:00 PM", title: "Intelligent Living", kannada: "ಬುದ್ಧಿವಂತ ಜೀವನ", tag: .vedic,
                      details: "By Swami Aparajitananda.",
                      icon: "hands.sparkles.fill", venue: "Ahichhatra Auditorium", isHighlight: true),
        ScheduleEvent(time: "9:00 AM – 12:00 PM", title: "Carnatic Classical Performances", kannada: "ಕರ್ನಾಟಕ ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತ", tag: .cultural,
                      details: "Carnatic classical performances by Detroit Chapter.",
                      icon: "music.note", chapter: "Detroit Chapter", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "9:00 AM – 12:00 PM", title: "Namma Ooru Namma Jana — Skit & Fashion Show", kannada: "ನಮ್ಮ ಊರು ನಮ್ಮ ಜನ", tag: .cultural,
                      details: "Skit and fashion show by Canada Chapter.",
                      icon: "theatermasks.fill", chapter: "Canada Chapter", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "9:00 AM – 12:00 PM", title: "Hima Maya", kannada: "ಹಿಮ ಮಾಯಾ", tag: .cultural,
                      details: "Dance drama production by Acharya Performing Arts Academy.",
                      icon: "figure.dance", venue: "Ahichhatra Auditorium", isHighlight: true),
        ScheduleEvent(time: "10:30 – 11:15 AM", title: "Satsang with Swami Aparajitananda & Q&A", kannada: "ಸ್ವಾಮಿ ಅಪರಾಜಿತಾನಂದರೊಂದಿಗೆ ಸತ್ಸಂಗ", tag: .vedic,
                      details: "Moderator: Suma Rajashankara.",
                      icon: "hands.sparkles.fill", venue: "Bharadvaja & Jamadagni Kutira"),
        ScheduleEvent(time: "12:00 – 1:30 PM", title: "Lunch", kannada: "ಭೋಜನ", tag: .meal,
                      details: "Full vegetarian lunch.",
                      icon: "fork.knife", venue: "Annapoorna Bhojana Shale (Gym)"),
        ScheduleEvent(time: "12:45 – 1:30 PM", title: "Upbringing Kids in America", kannada: "ಅಮೆರಿಕಾದಲ್ಲಿ ಮಕ್ಕಳ ಪೋಷಣೆ", tag: .youth,
                      details: "Moderator/Presenter: Sujatha Kanjarpane.",
                      icon: "figure.and.child.holdinghands", venue: "Bharadvaja & Jamadagni Kutira"),
        ScheduleEvent(time: "12:45 – 1:30 PM", title: "Havyaka Udyoga", kannada: "ಹವ್ಯಕ ಉದ್ಯೋಗ", tag: .meeting,
                      details: "Moderator/Presenter: Balakrishna Joshi.",
                      icon: "briefcase.fill", venue: "Bharadvaja & Jamadagni Kutira"),
        ScheduleEvent(time: "1:30 – 3:15 PM", title: "Youth Symphony", kannada: "ಯುವ ಸಿಮ್ಫನಿ", tag: .cultural,
                      details: "Special musical presentation by all chapter youth.",
                      icon: "music.quarternote.3", venue: "Ahichhatra Auditorium", isHighlight: true),
        ScheduleEvent(time: "1:30 – 3:15 PM", title: "Variety Show", kannada: "ವೈವಿಧ್ಯಮಯ ಪ್ರದರ್ಶನ", tag: .cultural,
                      details: "Variety show by Northeast Chapter.",
                      icon: "sparkles", chapter: "Northeast Chapter", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "1:30 – 3:15 PM", title: "Song Medley", kannada: "ಗೀತೆ ಮೇಳೆ", tag: .cultural,
                      details: "Song medley by Arizona Chapter.",
                      icon: "music.note.list", chapter: "Arizona Chapter", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "3:30 – 4:00 PM", title: "Tea Break", kannada: "ಚಹಾ ವಿರಾಮ", tag: .meal,
                      details: "Afternoon tea break.",
                      icon: "cup.and.saucer.fill", venue: "Havya Paakashale (Cafeteria)"),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Hindustani Classical", kannada: "ಹಿಂದುಸ್ತಾನಿ ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತ", tag: .cultural,
                      details: "Hindustani classical by New England Chapter.",
                      icon: "music.note", chapter: "New England Chapter", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Jugalbandi of Music", kannada: "ಸಂಗೀತ ಜುಗಲ್ಬಂದಿ", tag: .concert,
                      details: "Jugalbandi of music by Vinayak Hegde & Team.",
                      icon: "music.mic", venue: "Ahichhatra Auditorium", isHighlight: true),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Group Songs & Fashion Show", kannada: "ಗುಂಪು ಗೀತೆಗಳು ಮತ್ತು ಫ್ಯಾಷನ್ ಶೋ", tag: .cultural,
                      details: "Group songs and fashion show by Dallas Chapter.",
                      icon: "figure.dance", chapter: "Dallas Chapter", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Havyaka Danta Kathe — Skit", kannada: "ಹವ್ಯಕ ದಂತ ಕಥೆ", tag: .cultural,
                      details: "Skit presentation.",
                      icon: "theatermasks.fill", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Havyaka Samagamadalli Reels Baya — A Tapestry", kannada: "ಹವ್ಯಕ ಸಮಾಗಮದಲ್ಲಿ ರೀಲ್ಸ್ ಬಯ", tag: .cultural,
                      details: "A tapestry of performances.",
                      icon: "theatermasks.fill", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Samaropa Samarabha — Program Agenda", kannada: "ಸಮಾರೋಪ ಸಮಾರಂಭ", tag: .ceremony,
                      details: "Closing ceremony program agenda.",
                      icon: "list.bullet", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Convention Recap", kannada: "ಸಮ್ಮೇಳನ ಸಾರಾಂಶ", tag: .ceremony,
                      details: "HAA President.",
                      icon: "text.quote", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Handover the HAA Responsibility to Next President", kannada: "ಮುಂದಿನ ಅಧ್ಯಕ್ಷರಿಗೆ ಹವ್ಯಕ ಅಸೋಸಿಯೇಷನ್ ಜವಾಬ್ದಾರಿ ಹಸ್ತಾಂತರ", tag: .ceremony,
                      details: "Formal transition of HAA leadership.",
                      icon: "arrow.right.arrow.left", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Invitation to 2028 HAA Convention at Seattle", kannada: "೨೦೨೮ ಸಿಯಾಟಲ್ ಸಮ್ಮೇಳನಕ್ಕೆ ಆಹ್ವಾನ", tag: .ceremony,
                      details: "Invitation to the next biennial convention in Seattle.",
                      icon: "mappin.and.ellipse", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Recognize Newly Wed Couple — Meghana & Shreyas", kannada: "ನವ ವಿವಾಹಿತ ದಂಪತಿಗಳ ಗೌರವ", tag: .social,
                      details: "Community recognition of Meghana & Shreyas.",
                      icon: "heart.circle.fill", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "4:00 – 7:30 PM", title: "Vote of Thanks for the Convention", kannada: "ಧನ್ಯವಾದ", tag: .ceremony,
                      details: "HAA Secretary.",
                      icon: "hands.clap.fill", venue: "Ahichhatra Auditorium"),
        ScheduleEvent(time: "7:30 – 9:00 PM", title: "Reception Dinner Sponsored by Bhat & Kuloor Family", kannada: "ಭಟ್ ಮತ್ತು ಕುಲೂರ್ ಕುಟುಂಬದ ಪ್ರಾಯೋಜಿತ ಸಂಭ್ರಮ ಭೋಜನ", tag: .meal,
                      details: "Reception dinner sponsored by the Bhat & Kuloor Family.",
                      icon: "fork.knife", venue: "Annapoorna Bhojana Shale (Gym)", isHighlight: true),
        ScheduleEvent(time: "9:00 – 11:00 PM", title: "Yakshagana \"Veeramani Kalaga\"", kannada: "ಯಕ್ಷಗಾನ \"ವೀರಮಣಿ ಕಲಾಗ\"", tag: .cultural,
                      details: "Performed by Yakshamitra Toronto & US Artists.",
                      icon: "theatermasks.fill", venue: "Ahichhatra Auditorium", isHighlight: true),
        ScheduleEvent(time: "11:30 PM – 1:00 AM", title: "Open Dance Floor", kannada: "ಮುಕ್ತ ನೃತ್ಯ ಮೈದಾನ", tag: .social,
                      details: "Open dance floor for all attendees.",
                      icon: "figure.dance", venue: "Ahichhatra Auditorium"),
    ]

    static let sundayEvents: [ScheduleEvent] = [
        ScheduleEvent(time: "8:30 – 10:00 AM", title: "Breakfast", kannada: "ಉಪಾಹಾರ", tag: .meal,
                      details: "Final morning breakfast.",
                      icon: "sunrise.fill", venue: "Annapoorna Bhojana Shale (Gym)"),
        ScheduleEvent(time: "9:30 – 11:30 AM", title: "HAA General Body Meeting (GBM)", kannada: "ಸರ್ವ ಸದಸ್ಯ ಸಭೆ", tag: .meeting,
                      details: "Agenda: Financial Updates; Membership Fee & Convention Change Proposal; HAA's 10-Year Vision; Online Voting; HAA Office Bearers Selection; Convention Resolutions; Q&A.",
                      icon: "person.2.fill", venue: "Ahichhatra Auditorium", isHighlight: true),
        ScheduleEvent(time: "11:30 AM – 12:30 PM", title: "Lunch To Go", kannada: "ತೆಗೆದುಕೊಂಡು ಹೋಗುವ ಭೋಜನ", tag: .meal,
                      details: "Packaged lunch to take with you as you depart.",
                      icon: "bag.fill", venue: "Annapoorna Bhojana Shale (Gym)"),
    ]
}
